server:
  port: 8090

spring:
  application:
    name: starlink-juc-engine

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: slr-juc-engine
      auto-offset-reset: latest
      enable-auto-commit: true # 生产环境建议设为 false 并手动 ack

  redis:
    host: localhost
    port: 6379
    database: 0

logging:
  level:
    root: INFO
    com.liboshuai.slr: DEBUG